/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomNav: typeof import('./src/components/layout/BottomNav.vue')['default']
    DateHeader: typeof import('./src/components/today/DateHeader.vue')['default']
    ItemCard: typeof import('./src/components/today/ItemCard.vue')['default']
    ItemList: typeof import('./src/components/today/ItemList.vue')['default']
    MonthFilter: typeof import('./src/components/history/MonthFilter.vue')['default']
    QuickInput: typeof import('./src/components/today/QuickInput.vue')['default']
    RecordCard: typeof import('./src/components/history/RecordCard.vue')['default']
    ReviewSection: typeof import('./src/components/today/ReviewSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanDialog: typeof import('vant/es')['Dialog']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
